name: Code quality check

on: [pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup init_script
      shell: bash
      run: |
        echo "#!/bin/bash

        root_dir=\${1}
        build_dir=\${2}

        python3 -m venv "$HOME/venv"
        source "$HOME/venv/bin/activate"
        pip install --upgrade pip
        pip install conan PyGithub

        conan profile detect
        conan install \$root_dir --output-folder=build --build=missing --settings=build_type=Release -c tools.system.package_manager:mode=install


        wget https://sdk.lunarg.com/sdk/download/1.4.313.0/linux/vulkansdk-linux-x86_64-1.4.313.0.tar.xz
        mkdir vulkan
        tar xf vulkansdk-linux-x86_64-1.4.313.0.tar.xz -C \$root_dir/vulkan
        source \$root_dir/vulkan/1.4.313.0/setup-env.sh" > init_script.sh

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        exclude_dir: lib
        init_script: init_script.sh
        apt_pckgs: xorg-dev python3-pip python3.12-venv
        report_pr_changes_only: false
        cmake_args: -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
        verbose: true
        clang_tidy_args: "-extra-arg=-std=c++20 -extra-arg=-DFMT_USE_CONSTEVAL=0"
        cppcheck_args: >-
            --enable=all
            --suppress=missingIncludeSystem
            --suppress=unmatchedSuppression
            --suppress=checkersReport
            --suppress=unusedFunction
            --suppress=functionStatic
            --suppress=functionConst
            --suppress=constParameterPointer
            --suppress=returnByReference
            --suppress=funcArgNamesDifferent
            --inline-suppr
            --inconclusive
            --check-level=exhaustive
