name: Ubuntu

on:
  push:
    branches:
      - master
      - develop
  pull_request:

env:
  BUILD_TYPE: Release
  CXX: clang++-14

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xorg-dev llvm-dev python3-pip

        pip install conan

        wget https://sdk.lunarg.com/sdk/download/1.3.204.1/linux/vulkansdk-linux-x86_64-1.3.204.1.tar.gz
        tar xf vulkansdk-linux-x86_64-1.3.204.1.tar.gz

        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: |
        source ${{runner.workspace}}/Shady/1.3.204.1/setup-env.sh
        conan install $GITHUB_WORKSPACE --output-folder=build --build=missing --settings=build_type=Release
        cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNINGS_AS_ERRORS=ON \
        -DENABLE_INCLUDE_WHAT_YOU_USE=OFF -DUNITY_BUILD=ON -DASSIMP_BUILD_TESTS=0

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE 2> >(tee "output.txt")

    - name: Post PR comment for warnings/errors
      if: always() && github.ref != 'refs/heads/develop' && github.ref != 'refs/heads/master'
      uses: JacobDomagala/CompileResultAction@master
      with:
        comment_title: UBUNTU COMPILE RESULT
        compile_result_file: ${{runner.workspace}}/build/output.txt
